"""
query_executor.py — executes a SQL query against a SQLite database.

Uses parameterised queries where possible and returns results as a
pandas DataFrame so the dashboard can render them directly.

Public function:
  - execute(sql, db_path) → pandas.DataFrame
"""

import sqlite3
import pandas as pd


def execute(sql: str, db_path: str) -> pd.DataFrame:
    """
    Run a SQL query against a SQLite database and return the results.

    Only SELECT statements are permitted. Any attempt to run a data-modifying
    statement (INSERT, UPDATE, DELETE, DROP, etc.) is rejected before it
    reaches the database.

    Args:
        sql:     A SQL SELECT query string, typically generated by text_to_sql.py.
        db_path: Path to the SQLite .db file to query.

    Returns:
        A pandas DataFrame containing the query results. Returns an empty
        DataFrame (with columns) if the query matches no rows.

    Raises:
        ValueError: if the statement is not a SELECT query.
        sqlite3.OperationalError: if the SQL is syntactically invalid or
            references tables/columns that do not exist.
        sqlite3.DatabaseError: if the database file cannot be opened.
    """
    stripped = sql.strip().lstrip(";")

    if not stripped.upper().startswith("SELECT"):
        raise ValueError(
            f"[query_executor] Only SELECT queries are allowed. Got: {sql!r}"
        )

    print(f"[query_executor] Executing: {sql}")

    try:
        conn = sqlite3.connect(db_path)
        df = pd.read_sql_query(sql, conn)
        conn.close()
    except sqlite3.OperationalError as e:
        raise sqlite3.OperationalError(
            f"[query_executor] SQL error: {e}\nQuery: {sql}"
        ) from e
    except sqlite3.DatabaseError as e:
        raise sqlite3.DatabaseError(
            f"[query_executor] Could not open database '{db_path}': {e}"
        ) from e

    print(f"[query_executor] Returned {len(df)} row(s), {len(df.columns)} column(s).")
    return df
